# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "{{ author }}"
__copyright__ = "Copyright {{ year }}, {{ author }}"
__email__ = "{{ email }}"
__license__ = "GPL-3"

include: "rules/common.smk"

report: "report/workflow.rst"

rule dummy:
    output:
        "{{ short_name }}/dummy/{sample}_{type}.dummy.txt"
    params:
        extra=config.get("dummy", {}).get("extra", ""),
    log:
        "{{ short_name }}/dummy/{sample}_{type}.output.log"
    benchmark:
       repeat("module/dummy/{sample}_{type}.output.benchmark.tsv", config.get("dummy", {}).get("benchmark_repeats", 1),)
    threads: # optional
       config.get("dummy", config["default_resources"])["threads"]
    container:
       config.get("dummy", {}).get("container", config["default_container"])
    conda:
       "../envs/dummy.yaml"
    message:
       "{rule}: Do stuff on module/{rule}/{wildcards.sample}_{wildcards.type}.input"
    shell:
        """
        touch {output}
        """

rule all:
    input:
        unpack(compile_output_list),
