# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "{{ author }}"
__copyright__ = "Copyright {{ year }}, {{ author }}"
__email__ = "{{ email }}"
__license__ = "GPL-3"

include: "rules/common.smk"

report: "report/workflow.rst"

rule dummy:
    output:
        "dummy.txt"
    shell:
        """
        touch dummy.txt
        """

rule all:
    input:
        unpack(compile_output_list),
