name: Snakefmt

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches:
     - develop
     - main
  pull_request:
    branches:
     - develop
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snakefmt:
    name: Snakefmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4.9.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: {{ '${{' }} secrets.GITHUB_TOKEN {{'}}'}}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          DEFAULT_BRANCH: main
          OUTPUT_FOLDER: .github/linters/report
